version: '3.8'

services:
  floci-az:
    image: floci/floci-az:latest
    container_name: floci-az-emulator
    ports:
      - "4577:4577"
    environment:
      - DEFAULT_REGION=eastus
      - AZURE_CLIENT_ID=00000000-0000-0000-0000-000000000000
      - AZURE_CLIENT_SECRET=dummy-secret
      - AZURE_TENANT_ID=00000000-0000-0000-0000-000000000000
      - AZURE_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
      - FLOCI_AZ_TLS_ENABLED=true
      - FLOCI_AZ_HOSTNAME=localhost:4577
    volumes:
      - floci-data:/var/lib/floci/data

  # Floci Web Interface
  floci-ui:
    image: floci/floci-ui:latest
    container_name: floci-ui
    ports:
      - "4500:4500"
    environment:
      - FLOCI_AZ_ENDPOINT=http://floci-az:4577
    depends_on:
      - floci-az

  cosmos-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmos-emulator
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
    volumes:
      - cosmos-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  web-backend:
    build:
      context: ../web-backend
    container_name: web-backend
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      # Utiliza os nomes dos containers (resolução de DNS interna do Docker)
      - COSMOS_ENDPOINT=https://cosmos-emulator:8081
      - STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://floci-az:4577/devstoreaccount1;
      - RABBITMQ_CONNECTION_STRING=amqp://admin:admin@rabbitmq:5672/
    depends_on:
      - cosmos-emulator
      - rabbitmq
      - floci-az

  web-frontend:
    build:
      context: ../web-frontend
    container_name: web-frontend
    restart: on-failure
    ports:
      - "8080:80"
    depends_on:
      - web-backend

  worker-events:
    build:
      context: ../worker-events
    container_name: worker-events
    restart: on-failure
    environment:
      - RABBITMQ_CONNECTION_STRING=amqp://admin:admin@rabbitmq:5672/
    depends_on:
      - rabbitmq

volumes:
  floci-data:
  cosmos-data:
  rabbitmq-data:
