name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web-frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web-frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Docker build example
    - name: Build Docker image
      run: |
        cd web-frontend
        docker build -t my-registry.azurecr.io/web-frontend:${{ github.sha }} .
        # docker push my-registry.azurecr.io/web-frontend:${{ github.sha }}
        
    - name: Update GitOps Repo
      run: |
        echo "Here an automatic commit would occur in the gitops-argocd repo with the new web-frontend tag version."
