apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: events-api-secrets
  namespace: events-app
spec:
  refreshInterval: "1h"
  # O ClusterSecretStore é criado via Terraform/plataforma para cada env/region
  # e aponta para o Key Vault correspondente (ex: kv-uat-us-001)
  secretStoreRef:
    name: uat-us
    kind: ClusterSecretStore
  # O target é o nome do secret K8s nativo que será criado
  target:
    name: events-api-secrets-k8s
    creationPolicy: Owner
  data:
  - secretKey: COSMOS_CONNECTION_STRING
    remoteRef:
      key: cosmos-connection-string
  - secretKey: REDIS_CONNECTION_STRING
    remoteRef:
      key: redis-connection-string
  - secretKey: RABBITMQ_CONNECTION_STRING
    remoteRef:
      key: rabbitmq-connection-string
  - secretKey: EVENTHUB_CONNECTION_STRING
    remoteRef:
      key: eventhub-connection-string
  - secretKey: STORAGE_CONNECTION_STRING
    remoteRef:
      key: storage-connection-string
